general:
    resource: "@GeneralBundle/Resources/config/routing.yml"
    prefix:   /

empresa:
    resource: "@EmpresaBundle/Resources/config/routing.yml"
    prefix:   /

equipo:
    resource: "@EquipoBundle/Resources/config/routing.yml"
    prefix:   /

cliente:
    resource: "@ClienteBundle/Resources/config/routing.yml"
    prefix:   /

fabricante:
    resource: "@FabricanteBundle/Resources/config/routing.yml"
    prefix:   /

personal:
    resource: "@PersonalBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
