rol:
    path:     /
    defaults: { _controller: "PersonalBundle:rol:index" }

rol_show:
    path:     /{id}/show
    defaults: { _controller: "PersonalBundle:rol:show" }

rol_new:
    path:     /new
    defaults: { _controller: "PersonalBundle:rol:new" }

rol_create:
    path:     /create
    defaults: { _controller: "PersonalBundle:rol:create" }
    methods:  POST

rol_edit:
    path:     /{id}/edit
    defaults: { _controller: "PersonalBundle:rol:edit" }

rol_update:
    path:     /{id}/update
    defaults: { _controller: "PersonalBundle:rol:update" }
    methods:  [POST, PUT]

rol_delete:
    path:     /{id}/delete
    defaults: { _controller: "PersonalBundle:rol:delete" }
    methods:  [POST, DELETE]
